### PR TITLE
Added project link to Dutch PDOK map module

### PR DESCRIPTION
**Pull request by Sidiox**
Adds link to FarmOS Map module adding support for the Dutch PDOK open data map layers.

### CODE REVIEW

**Comment by mstenta** [comment]
Awesome! Thanks @Sidiox!

PS: I also added your module to the list of contrib modules we are tracking for farmOS 2.x upgrade paths: https://www.drupal.org/project/farm/issues/3151247

Once we have some of the other ones ported it should be pretty easy for you to follow the same pattern to create a 2.x version as well.

**Comment by Sidiox** [comment]
I'd be happy to already make sure I have a branch working with the farmOS 2.x project, I take it I can just take the 2.x branch to get going?

**Comment by mstenta** [comment]
That would be great! But we haven't quite gotten that far yet on our end. :-)

We need to establish the template for making map layer modules like this. Should get around to that pretty soon! Focusing on data architecture + migration paths + API for alpha1, then we can turn attention to more of the frontend bits.

I plan to port a few of the other `farm_map_*` modules when that time comes, so that will give you something to work from.

Standby!

**Comment by mstenta** [comment]
PS: You can "follow" that drupal.org issue for updates - I'll comment when some of those other modules are ported. That might be the best way to get notified.

**Pull request merged**
