### PR TITLE
Modified sensors.md to add a link to a demo video

### PR DESCRIPTION
**Pull request by dwblair**

### CODE REVIEW

**Comment by mstenta** [comment]
Woo hoo! Thanks @dwblair ! This is a great intro to posting data.

What do you think about just embedding this video directly in the page via iframe? That's what we do for the other videos on the sensors page (eg: https://farmos.org/guide/assets/sensors/#grovepi-node-red and https://farmos.org/guide/assets/sensors/#open-pipe-kit)

I think it would just be:

```
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/arGErKKODrU" allowfullscreen></iframe> 
```

**Comment by dwblair** [comment]
Yesssss that's elegant, lemme do that!

**Comment by dwblair** [comment]
.... I think I've done it?  do you get a notification that I made changes? Still learning how this works!

**Comment by mstenta** [comment]
Yes! Perfect! Merged!

Thanks again @dwblair !

**Comment by mstenta** [comment]
(PS we have a nifty GitHub Action set up that will automatically run Mkdocs to convert markdown to HTML and deploy this to farmOS.org - so it should be live shortly......)

https://github.com/farmOS/farmOS.org/runs/706078923

**Comment by dwblair** [comment]
Oh that's so cool!

**Pull request merged**
