### PR TITLE
Add documentation for OAuth

### PR DESCRIPTION
**Pull request by paul121**
Starting a PR that adds OAuth Documentation. We had talked about creating a separate Authorization and Authentication category separate from the API page, but decided to include under `/development/api` for now.

### CODE REVIEW

**Comment by paul121** [comment]
I added a section to document the Authorization procedure within the API Client Libraries. I think it would be useful to include a brief explanation of that process here, and link to the API Libraries for more info.

**Comment by mstenta** [comment]
Great start!

Let's not forget to fill in the **OAuth2 Authorization with the farmOS API**,  **Authorization in farmOS.py**, and **Authorization in farmOS.js** sections before merging this in.

And this also needs to wait for us to merge OAuth stuff into farmOS itself as well, of course. :-)

**Comment by mstenta** [comment]
Thanks @paul121 - reviewing this now that https://github.com/farmOS/farmOS/pull/207 is merged.

My plan is to merge this into a 7.x-1.4 branch of the farmOS.org repo, to be deployed when farmOS 7.x-1.4 is officially released.

**Comment by mstenta** [comment]
I'm making some changes to this locally... will push soon.

**Comment by mstenta** [comment]
I created a new `7.x-1.4` branch and merged this into this, along with some minimal changes and additions. Thanks again @paul121 !

**Comment by mstenta** [comment]
See: https://github.com/farmOS/farmOS.org/compare/7.x-1.4

**Pull request closed without merging**
