### PR TITLE
Add Drush info to docker documentation

### PR DESCRIPTION
**Pull request by paul121**

### CODE REVIEW

**Comment by mstenta** [comment]
Awesome! This will be a great addition.

Two small requests: can you break lines at 80 characters, and put the Drush link URL at the bottom of the file (for consistency with the rest of the docs)?

Also, we should mention that the farmOS container will be named `farmos_www_1` ONLY if your farmOS directory is named `farmOS`. Docker Compose names the containers based on the folder that they are in, so if you name your folder `myfarmOS` then the container will be named `myfarmos_www_1`.

**Comment by paul121** [comment]
Done. That is a slick way of handling the links - I hadn't noticed that!

Also good to know on Docker Compose -  I didn't realize it used the folder name for containers. Thanks!

**Comment by mstenta** [comment]
Thanks! Merged!

I removed the `exec bash` command - that's not necessary. Once you have an alias it will run drush in the container and show you the output in your terminal. No need to get into the bash shell inside the container first.

**Comment by paul121** [comment]
@mstenta ah, I included `exec bash` just to reload changes of the `.bashrc` file. Does that make sense? I _believe_ it is necessary, but not sure...

**Comment by mstenta** [comment]
Oh gotcha - that makes sense. Didn't know you could do that - I usually run `source ~/.bashrc` to reload (or just load a new terminal). I think we can omit that from the docs.

**Pull request closed without merging**
